spring:
  application:
    name: gateway-server

  config:
    import: optional:configserver:http://localhost:8082
  #cloud:
    #config:
      #enabled: true
      #uri: http://localhost:8082

  cloud:
    gateway:
      routes:
#        - id: getAllAccounts-v1
#          uri: http://localhost:8091
#          predicates:
#          - Path=/account/getAll
#
#        - id: getAllAccounts-v2
#          uri: http://localhost:8091
#          predicates:
#          - Path=/getAll
#          filters:
#          - PrefixPath=/account
#
#        - id: getAllAccounts-v3
#          uri: http://localhost:8091
#          predicates:
#          - Path=/getAllAccounts, /Accounts, /Accnts
#          filters:
#          - SetPath=/account/getAll

        - id: Accounts-v1
          uri: lb://ms-account
          predicates:
          - Path=/account/**

        - id: Customers-v1
          uri: lb://ms-customer
          predicates:
          - Path=/customer/**

        - id: Credits-v1
          uri: lb://ms-credit
          predicates:
          - Path=/credit/**

        - id: Payments-v1
          uri: lb://ms-payment
          predicates:
          - Path=/payment/**

        - id: Transactions-v1
          uri: lb://ms-transaction
          predicates:
          - Path=/transaction/**