spring:
  application:
    name: gateway-server

  config:
    import: optional:configserver:http://localhost:8082
  #cloud:
    #config:
      #enabled: true
      #uri: http://localhost:8082

  cloud:
    gateway:
      routes:
#        - id: getAllAccounts-v1
#          uri: http://localhost:8091
#          predicates:
#          - Path=/account/getAll
#
#        - id: getAllAccounts-v2
#          uri: http://localhost:8091
#          predicates:
#          - Path=/getAll
#          filters:
#          - PrefixPath=/account
#
#        - id: getAllAccounts-v3
#          uri: http://localhost:8091
#          predicates:
#          - Path=/getAllAccounts, /Accounts, /Accnts
#          filters:
#          - SetPath=/account/getAll

        - id: getAllAccounts-v4
          uri: lb://ms-account
          predicates:
          - Path=/account/**